### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [kulkansecurity/gitxray#1]
It would be very helpful if you could tag releases as well. This would enable distributions who want to fetch the package from GitHub instead of PyPI.

Thanks

**Comment by llavarello** [comment]
@fabaff thanks for pointing that out! I'll do so for the upcoming release.

**Comment by llavarello** [comment]
@fabaff - Please, when possible, see if the release I just created fits the use-case you described please. Thank you!

**Comment by fabaff** [comment]
Thanks @llavarello.

Work fine (https://github.com/NixOS/nixpkgs/pull/349773)
