### ISSUE TITLE
Parameters -r -o -c, should not require "https://github.com"

### ISSUE THREAD

**Issue by mattaereal** [kulkansecurity/gitxray#3]
It's annoying, we're working with GitHub, so if you ask them to start with https:// then aren't they all going to be https://github.com? Is there a case I'm missing? It would be nice to be implicit.

**Comment by llavarello** [comment]
@mattaereal certainly! Expect a brand new version (which also brings a rocking HTML report) soon. I'll include your suggested change as well. Thank you!

**Comment by llavarello** [comment]
@mattaereal - Please check out v1.0.16 - Already includes your suggested change. I've tagged you in the Changelog. Thanks!

**Comment by mattaereal** [comment]
Thanks! :) Will you update the PyPi as well? I have a Dockerfile with hardcoded latest stable version tested by myself

**Comment by llavarello** [comment]
Yes sir, already pushed to PyPi - upgrade to v1.0.16 with:
pip install gitxray --upgrade
