### ISSUE TITLE
Release may not have an author

### ISSUE THREAD

**Issue by fearcito** [kulkansecurity/gitxray#5]
Using version 16.0.2, to reproduce:

`gitxray -r https://github.com/${{REPO}} -f emails -outformat text -out filters.log`

Stderr:
```
Traceback (most recent call last):
  File "/usr/local/bin/gitxray", line 8, in <module>
    sys.exit(gitxray_cli())
             ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/gitxray/gitxray.py", line 91, in gitxray_cli
    if not repository_xray.run(gx_context, gx_output): continue
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gitxray/xrays/repository_xray.py", line 243, in run
    if release.get('author') == None:
       ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by llavarello** [comment]
@fearcito I'm trying to replicate but can't. Any chance you can try again? Thanks!

**Comment by fearcito** [comment]
I can't reproduce it when using the Github token (it works as expected), but when not being authenticated it crashes when fetching `web/releases`

**Comment by llavarello** [comment]
@fearcito can you please try the code in main? Just submitted a potential ugly patch.

**Comment by fearcito** [comment]
@llavarello 3 things:
- The patch works beautifully
- It was possible to compile from sources as expected to test the patch, all good on that area as well
- Running it authenticated worked very, very well. I successfully executed gitxray in parallel authenticated at a great speed, much faster than unauthenticated.

**Comment by llavarello** [comment]
That's excellent news! I just pushed v1.0.16.4 to pypi and created the release here as well. 

Enjoy your X-Rays! Closing this Issue for now.
